spring:
  resources:
    static-locations=classpath:/static/:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot
    username: root
    password: rladnwls1004@
  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
chatgpt:
  api-key: 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
server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:bootsecurity.p12
    key-store-password: mujyan
    key-store-type: PKCS12
    key-alias: bootsecurity